stages:
  - oxeye_code_scan
variables:
  OXEYE_SCAN_OXEYE_URL: api.oxeye.net
  OXEYE_SCAN_GITLAB_TOKEN: ''
  OXEYE_SCAN_CLIENT_ID: ''
  OXEYE_SCAN_SECRET: ''
  OXEYE_SCAN_WORKSPACE_ID: ''
  OXEYE_SCAN_RELEASE: ''
oxeye_code_scan:
  stage: oxeye_code_scan
  image:
    name: ghcr.io/ox-eye/github-actions/oxeye-scan:v0.0.8
    entrypoint:
      - /bin/sh
      - '-c'
  script:
    - /entrypoint.sh ${OXEYE_SCAN_GITLAB_TOKEN} ${OXEYE_SCAN_OXEYE_URL} ${OXEYE_SCAN_CLIENT_ID} ${OXEYE_SCAN_SECRET} ${OXEYE_SCAN_WORKSPACE_ID} ${OXEYE_SCAN_RELEASE}
